-- Expanded action coverage for the top 10 integrations.
-- Researched from n8n's nodes-base for action shape; re-implemented here as
-- our manifest format. All entries are upserts of EXISTING integration rows,
-- replacing their `manifest.actions` array with the fuller set.
--
-- Idempotent: ON CONFLICT (slug) DO UPDATE replaces the manifest each run.

-- ============ SLACK ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key",
    "fields":[{"name":"bot_token","label":"Bot User OAuth Token",
                "help":"Get from api.slack.com -> Your App -> OAuth & Permissions. Starts with xoxb-..."}]},
  "actions":[
    {"name":"post_message","label":"Send message to channel",
      "inputs":[{"name":"channel","type":"string","required":true,"help":"#channel-name, channel id, or @user"},
                 {"name":"text","type":"string","required":true},
                 {"name":"thread_ts","type":"string","help":"Optional thread parent timestamp"}],
      "outputs":[{"name":"ts","type":"string"},{"name":"channel","type":"string"}]},
    {"name":"update_message","label":"Update a sent message",
      "inputs":[{"name":"channel","type":"string","required":true},
                 {"name":"ts","type":"string","required":true},
                 {"name":"text","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://slack.com/api/chat.update",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}","Content-Type":"application/json"},
        "body":"{\"channel\":\"{{ input.channel }}\",\"ts\":\"{{ input.ts }}\",\"text\":\"{{ input.text }}\"}"},
      "response_map":{"ok":"$.ok"}},
    {"name":"delete_message","label":"Delete a message",
      "inputs":[{"name":"channel","type":"string","required":true},
                 {"name":"ts","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://slack.com/api/chat.delete",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}","Content-Type":"application/json"},
        "body":"{\"channel\":\"{{ input.channel }}\",\"ts\":\"{{ input.ts }}\"}"},
      "response_map":{"ok":"$.ok"}},
    {"name":"get_permalink","label":"Get message permalink",
      "inputs":[{"name":"channel","type":"string","required":true},
                 {"name":"ts","type":"string","required":true}],
      "outputs":[{"name":"permalink","type":"string"}],
      "request":{"method":"GET",
        "url":"https://slack.com/api/chat.getPermalink?channel={{ input.channel }}&message_ts={{ input.ts }}",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}"}},
      "response_map":{"permalink":"$.permalink"}},
    {"name":"search","label":"Search messages",
      "inputs":[{"name":"query","type":"string","required":true}],
      "outputs":[{"name":"messages","type":"array"}],
      "request":{"method":"GET",
        "url":"https://slack.com/api/search.messages?query={{ input.query }}",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}"}},
      "response_map":{"messages":"$.messages.matches"}},
    {"name":"add_reaction","label":"Add emoji reaction",
      "inputs":[{"name":"channel","type":"string","required":true},
                 {"name":"timestamp","type":"string","required":true},
                 {"name":"name","type":"string","required":true,"help":"Emoji name without colons"}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://slack.com/api/reactions.add",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}","Content-Type":"application/json"},
        "body":"{\"channel\":\"{{ input.channel }}\",\"timestamp\":\"{{ input.timestamp }}\",\"name\":\"{{ input.name }}\"}"},
      "response_map":{"ok":"$.ok"}},
    {"name":"channel_create","label":"Create channel",
      "inputs":[{"name":"name","type":"string","required":true},
                 {"name":"is_private","type":"bool","default":false}],
      "outputs":[{"name":"id","type":"string"}],
      "request":{"method":"POST","url":"https://slack.com/api/conversations.create",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}","Content-Type":"application/json"},
        "body":"{\"name\":\"{{ input.name }}\",\"is_private\":{{ input.is_private }}}"},
      "response_map":{"id":"$.channel.id"}},
    {"name":"channel_archive","label":"Archive channel",
      "inputs":[{"name":"channel","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://slack.com/api/conversations.archive",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}","Content-Type":"application/json"},
        "body":"{\"channel\":\"{{ input.channel }}\"}"},
      "response_map":{"ok":"$.ok"}},
    {"name":"channel_invite","label":"Invite user to channel",
      "inputs":[{"name":"channel","type":"string","required":true},
                 {"name":"users","type":"string","required":true,"help":"Comma-separated user IDs"}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://slack.com/api/conversations.invite",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}","Content-Type":"application/json"},
        "body":"{\"channel\":\"{{ input.channel }}\",\"users\":\"{{ input.users }}\"}"},
      "response_map":{"ok":"$.ok"}},
    {"name":"channel_list","label":"List channels",
      "inputs":[{"name":"limit","type":"int","default":100}],
      "outputs":[{"name":"channels","type":"array"}],
      "request":{"method":"GET",
        "url":"https://slack.com/api/conversations.list?limit={{ input.limit }}",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}"}},
      "response_map":{"channels":"$.channels"}},
    {"name":"user_info","label":"Get user info",
      "inputs":[{"name":"user","type":"string","required":true}],
      "outputs":[{"name":"user","type":"object"}],
      "request":{"method":"GET",
        "url":"https://slack.com/api/users.info?user={{ input.user }}",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}"}},
      "response_map":{"user":"$.user"}},
    {"name":"user_list","label":"List workspace users",
      "inputs":[],
      "outputs":[{"name":"members","type":"array"}],
      "request":{"method":"GET","url":"https://slack.com/api/users.list",
        "headers":{"Authorization":"Bearer {{ auth.bot_token }}"}},
      "response_map":{"members":"$.members"}}
  ]
}'::jsonb WHERE slug = 'slack';

-- ============ GMAIL ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"oauth_passthrough","provider":"google"},
  "actions":[
    {"name":"list_messages","label":"List messages",
      "inputs":[{"name":"query","type":"string","default":"is:unread"},
                 {"name":"limit","type":"int","default":25}],
      "outputs":[{"name":"messages","type":"array"}]},
    {"name":"get_message","label":"Get full message by id",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"message","type":"object"}]},
    {"name":"send_email","label":"Send email",
      "inputs":[{"name":"to","type":"string","required":true},
                 {"name":"subject","type":"string","required":true},
                 {"name":"body","type":"string","required":true},
                 {"name":"cc","type":"string"},
                 {"name":"bcc","type":"string"}],
      "outputs":[{"name":"message_id","type":"string"}]},
    {"name":"reply_email","label":"Reply to a thread",
      "inputs":[{"name":"message_id","type":"string","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"thread_id","type":"string"}]},
    {"name":"forward_email","label":"Forward an email",
      "inputs":[{"name":"message_id","type":"string","required":true},
                 {"name":"to","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"trash_email","label":"Move to trash",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"mark_read","label":"Mark as read",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"mark_unread","label":"Mark as unread",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"add_label","label":"Add label to message",
      "inputs":[{"name":"message_id","type":"string","required":true},
                 {"name":"label","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"create_draft","label":"Create draft",
      "inputs":[{"name":"to","type":"string","required":true},
                 {"name":"subject","type":"string","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"draft_id","type":"string"}]},
    {"name":"list_labels","label":"List labels",
      "inputs":[],
      "outputs":[{"name":"labels","type":"array"}]},
    {"name":"list_threads","label":"List threads",
      "inputs":[{"name":"query","type":"string"},
                 {"name":"limit","type":"int","default":25}],
      "outputs":[{"name":"threads","type":"array"}]}
  ]
}'::jsonb WHERE slug = 'gmail';

-- ============ OUTLOOK ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"oauth_passthrough","provider":"microsoft"},
  "actions":[
    {"name":"list_messages","label":"List messages",
      "inputs":[{"name":"query","type":"string"},
                 {"name":"max_days_old","type":"int"},
                 {"name":"limit","type":"int","default":25}],
      "outputs":[{"name":"messages","type":"array"}]},
    {"name":"get_message","label":"Get full message",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"message","type":"object"}]},
    {"name":"send_email","label":"Send email",
      "inputs":[{"name":"to","type":"string","required":true},
                 {"name":"subject","type":"string","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"reply_email","label":"Reply to message",
      "inputs":[{"name":"message_id","type":"string","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"mark_read","label":"Mark message as read",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"move_message","label":"Move to folder",
      "inputs":[{"name":"message_id","type":"string","required":true},
                 {"name":"destination_folder_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"delete_message","label":"Delete message",
      "inputs":[{"name":"message_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"list_folders","label":"List mail folders",
      "inputs":[],
      "outputs":[{"name":"folders","type":"array"}]},
    {"name":"create_folder","label":"Create mail folder",
      "inputs":[{"name":"display_name","type":"string","required":true}],
      "outputs":[{"name":"id","type":"string"}]},
    {"name":"create_draft","label":"Create draft message",
      "inputs":[{"name":"to","type":"string","required":true},
                 {"name":"subject","type":"string","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"draft_id","type":"string"}]}
  ]
}'::jsonb WHERE slug = 'outlook';

-- ============ NOTION ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key",
    "fields":[{"name":"integration_token","label":"Internal Integration Token",
                "help":"Get from notion.so/my-integrations"}]},
  "actions":[
    {"name":"create_page","label":"Create page in database",
      "inputs":[{"name":"parent_database_id","type":"string","required":true},
                 {"name":"title","type":"string","required":true},
                 {"name":"properties","type":"object"}],
      "outputs":[{"name":"page_id","type":"string"},{"name":"url","type":"string"}]},
    {"name":"create_page_in_page","label":"Create sub-page inside a page",
      "inputs":[{"name":"parent_page_id","type":"string","required":true},
                 {"name":"title","type":"string","required":true}],
      "outputs":[{"name":"page_id","type":"string"}],
      "request":{"method":"POST","url":"https://api.notion.com/v1/pages",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28","Content-Type":"application/json"},
        "body":"{\"parent\":{\"page_id\":\"{{ input.parent_page_id }}\"},\"properties\":{\"title\":{\"title\":[{\"text\":{\"content\":\"{{ input.title }}\"}}]}}}"},
      "response_map":{"page_id":"$.id"}},
    {"name":"append_text","label":"Append paragraph to page",
      "inputs":[{"name":"page_id","type":"string","required":true},
                 {"name":"text","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"append_heading","label":"Append heading to page",
      "inputs":[{"name":"page_id","type":"string","required":true},
                 {"name":"text","type":"string","required":true},
                 {"name":"level","type":"int","default":2}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"PATCH","url":"https://api.notion.com/v1/blocks/{{ input.page_id }}/children",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28","Content-Type":"application/json"},
        "body":"{\"children\":[{\"object\":\"block\",\"type\":\"heading_{{ input.level }}\",\"heading_{{ input.level }}\":{\"rich_text\":[{\"type\":\"text\",\"text\":{\"content\":\"{{ input.text }}\"}}]}}]}"},
      "response_map":{"ok":"$"}},
    {"name":"append_todo","label":"Append to-do block",
      "inputs":[{"name":"page_id","type":"string","required":true},
                 {"name":"text","type":"string","required":true},
                 {"name":"checked","type":"bool","default":false}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"PATCH","url":"https://api.notion.com/v1/blocks/{{ input.page_id }}/children",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28","Content-Type":"application/json"},
        "body":"{\"children\":[{\"object\":\"block\",\"type\":\"to_do\",\"to_do\":{\"rich_text\":[{\"type\":\"text\",\"text\":{\"content\":\"{{ input.text }}\"}}],\"checked\":{{ input.checked }}}}]}"},
      "response_map":{"ok":"$"}},
    {"name":"query_database","label":"Query database",
      "inputs":[{"name":"database_id","type":"string","required":true},
                 {"name":"page_size","type":"int","default":25}],
      "outputs":[{"name":"results","type":"array"}],
      "request":{"method":"POST","url":"https://api.notion.com/v1/databases/{{ input.database_id }}/query",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28","Content-Type":"application/json"},
        "body":"{\"page_size\":{{ input.page_size }}}"},
      "response_map":{"results":"$.results"}},
    {"name":"get_page","label":"Get page",
      "inputs":[{"name":"page_id","type":"string","required":true}],
      "outputs":[{"name":"page","type":"object"}],
      "request":{"method":"GET","url":"https://api.notion.com/v1/pages/{{ input.page_id }}",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28"}},
      "response_map":{"page":"$"}},
    {"name":"update_page_properties","label":"Update page properties",
      "inputs":[{"name":"page_id","type":"string","required":true},
                 {"name":"properties","type":"object","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"PATCH","url":"https://api.notion.com/v1/pages/{{ input.page_id }}",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28","Content-Type":"application/json"},
        "body":"{\"properties\":{{ input.properties }}}"},
      "response_map":{"ok":"$"}},
    {"name":"search","label":"Search Notion",
      "inputs":[{"name":"query","type":"string","required":true}],
      "outputs":[{"name":"results","type":"array"}],
      "request":{"method":"POST","url":"https://api.notion.com/v1/search",
        "headers":{"Authorization":"Bearer {{ auth.integration_token }}","Notion-Version":"2022-06-28","Content-Type":"application/json"},
        "body":"{\"query\":\"{{ input.query }}\"}"},
      "response_map":{"results":"$.results"}}
  ]
}'::jsonb WHERE slug = 'notion';

-- ============ TELEGRAM ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"oauth_passthrough","provider":"telegram"},
  "actions":[
    {"name":"send_message","label":"Send text message",
      "inputs":[{"name":"text","type":"string","required":true},
                 {"name":"parse_mode","type":"string","default":"HTML","help":"HTML, Markdown, or empty"},
                 {"name":"disable_preview","type":"bool","default":false}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"send_photo","label":"Send photo by URL",
      "inputs":[{"name":"photo_url","type":"string","required":true},
                 {"name":"caption","type":"string"}],
      "outputs":[{"name":"message_id","type":"int"}]},
    {"name":"send_document","label":"Send file by URL",
      "inputs":[{"name":"document_url","type":"string","required":true},
                 {"name":"caption","type":"string"}],
      "outputs":[{"name":"message_id","type":"int"}]},
    {"name":"send_location","label":"Send location",
      "inputs":[{"name":"latitude","type":"number","required":true},
                 {"name":"longitude","type":"number","required":true}],
      "outputs":[{"name":"message_id","type":"int"}]},
    {"name":"send_poll","label":"Send poll",
      "inputs":[{"name":"question","type":"string","required":true},
                 {"name":"options","type":"array","required":true}],
      "outputs":[{"name":"message_id","type":"int"}]}
  ]
}'::jsonb WHERE slug = 'telegram';

-- ============ DISCORD ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key",
    "fields":[{"name":"webhook_url","label":"Discord Webhook URL"}]},
  "actions":[
    {"name":"post_message","label":"Post a message",
      "inputs":[{"name":"text","type":"string","required":true},
                 {"name":"username","type":"string","help":"Override bot display name"},
                 {"name":"avatar_url","type":"string","help":"Override avatar"}],
      "outputs":[{"name":"ok","type":"boolean"}]},
    {"name":"post_embed","label":"Post a rich embed",
      "inputs":[{"name":"title","type":"string","required":true},
                 {"name":"description","type":"string"},
                 {"name":"color","type":"int","default":16753920,"help":"Decimal color, e.g. 16753920 = #FF9900"},
                 {"name":"url","type":"string","help":"Optional clickable URL"}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"{{ auth.webhook_url }}",
        "headers":{"Content-Type":"application/json"},
        "body":"{\"embeds\":[{\"title\":\"{{ input.title }}\",\"description\":\"{{ input.description }}\",\"color\":{{ input.color }},\"url\":\"{{ input.url }}\"}]}"},
      "response_map":{"ok":"$"}},
    {"name":"post_tts","label":"Post message as text-to-speech",
      "inputs":[{"name":"text","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"{{ auth.webhook_url }}",
        "headers":{"Content-Type":"application/json"},
        "body":"{\"content\":\"{{ input.text }}\",\"tts\":true}"},
      "response_map":{"ok":"$"}}
  ]
}'::jsonb WHERE slug = 'discord';

-- ============ LINEAR ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key",
    "fields":[{"name":"api_key","label":"Personal API Key","help":"linear.app/settings/api"}]},
  "actions":[
    {"name":"create_issue","label":"Create issue",
      "inputs":[{"name":"team_id","type":"string","required":true},
                 {"name":"title","type":"string","required":true},
                 {"name":"description","type":"string"}],
      "outputs":[{"name":"issue_id","type":"string"},{"name":"url","type":"string"}]},
    {"name":"update_issue","label":"Update issue",
      "inputs":[{"name":"issue_id","type":"string","required":true},
                 {"name":"title","type":"string"},
                 {"name":"description","type":"string"},
                 {"name":"state_id","type":"string"}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://api.linear.app/graphql",
        "headers":{"Authorization":"{{ auth.api_key }}","Content-Type":"application/json"},
        "body":"{\"query\":\"mutation { issueUpdate(id: \\\"{{ input.issue_id }}\\\", input: {title: \\\"{{ input.title }}\\\", description: \\\"{{ input.description }}\\\", stateId: \\\"{{ input.state_id }}\\\"}) { success } }\"}"},
      "response_map":{"ok":"$.data.issueUpdate.success"}},
    {"name":"add_comment","label":"Add comment to issue",
      "inputs":[{"name":"issue_id","type":"string","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"POST","url":"https://api.linear.app/graphql",
        "headers":{"Authorization":"{{ auth.api_key }}","Content-Type":"application/json"},
        "body":"{\"query\":\"mutation { commentCreate(input: {issueId: \\\"{{ input.issue_id }}\\\", body: \\\"{{ input.body }}\\\"}) { success } }\"}"},
      "response_map":{"ok":"$.data.commentCreate.success"}},
    {"name":"list_teams","label":"List teams",
      "inputs":[],
      "outputs":[{"name":"teams","type":"array"}],
      "request":{"method":"POST","url":"https://api.linear.app/graphql",
        "headers":{"Authorization":"{{ auth.api_key }}","Content-Type":"application/json"},
        "body":"{\"query\":\"{ teams { nodes { id name key } } }\"}"},
      "response_map":{"teams":"$.data.teams.nodes"}},
    {"name":"list_my_issues","label":"List my open issues",
      "inputs":[{"name":"limit","type":"int","default":25}],
      "outputs":[{"name":"issues","type":"array"}],
      "request":{"method":"POST","url":"https://api.linear.app/graphql",
        "headers":{"Authorization":"{{ auth.api_key }}","Content-Type":"application/json"},
        "body":"{\"query\":\"{ viewer { assignedIssues(first: {{ input.limit }}, filter: {state: {type: {nin: [\\\"completed\\\",\\\"canceled\\\"]}}}) { nodes { id identifier title url } } } }\"}"},
      "response_map":{"issues":"$.data.viewer.assignedIssues.nodes"}}
  ]
}'::jsonb WHERE slug = 'linear';

-- ============ TRELLO ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key",
    "fields":[{"name":"api_key","label":"API Key"},
               {"name":"token","label":"Token"}]},
  "actions":[
    {"name":"create_card","label":"Create card",
      "inputs":[{"name":"list_id","type":"string","required":true},
                 {"name":"name","type":"string","required":true},
                 {"name":"desc","type":"string"}],
      "outputs":[{"name":"card_id","type":"string"},{"name":"url","type":"string"}]},
    {"name":"update_card","label":"Update card",
      "inputs":[{"name":"card_id","type":"string","required":true},
                 {"name":"name","type":"string"},
                 {"name":"desc","type":"string"},
                 {"name":"closed","type":"bool"}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"PUT",
        "url":"https://api.trello.com/1/cards/{{ input.card_id }}?key={{ auth.api_key }}&token={{ auth.token }}&name={{ input.name }}&desc={{ input.desc }}&closed={{ input.closed }}"},
      "response_map":{"ok":"$.id"}},
    {"name":"delete_card","label":"Delete card",
      "inputs":[{"name":"card_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"DELETE",
        "url":"https://api.trello.com/1/cards/{{ input.card_id }}?key={{ auth.api_key }}&token={{ auth.token }}"},
      "response_map":{"ok":"$"}},
    {"name":"add_comment","label":"Add comment to card",
      "inputs":[{"name":"card_id","type":"string","required":true},
                 {"name":"text","type":"string","required":true}],
      "outputs":[{"name":"comment_id","type":"string"}],
      "request":{"method":"POST",
        "url":"https://api.trello.com/1/cards/{{ input.card_id }}/actions/comments?key={{ auth.api_key }}&token={{ auth.token }}&text={{ input.text }}"},
      "response_map":{"comment_id":"$.id"}},
    {"name":"list_lists","label":"List lists in a board",
      "inputs":[{"name":"board_id","type":"string","required":true}],
      "outputs":[{"name":"lists","type":"array"}],
      "request":{"method":"GET",
        "url":"https://api.trello.com/1/boards/{{ input.board_id }}/lists?key={{ auth.api_key }}&token={{ auth.token }}"},
      "response_map":{"lists":"$"}},
    {"name":"list_cards","label":"List cards in a list",
      "inputs":[{"name":"list_id","type":"string","required":true}],
      "outputs":[{"name":"cards","type":"array"}],
      "request":{"method":"GET",
        "url":"https://api.trello.com/1/lists/{{ input.list_id }}/cards?key={{ auth.api_key }}&token={{ auth.token }}"},
      "response_map":{"cards":"$"}}
  ]
}'::jsonb WHERE slug = 'trello';

-- ============ GITHUB ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key","fields":[{"name":"token","label":"Personal Access Token"}]},
  "actions":[
    {"name":"create_issue","label":"Create issue",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true},
                 {"name":"title","type":"string","required":true},
                 {"name":"body","type":"string"}],
      "outputs":[{"name":"number","type":"int"},{"name":"url","type":"string"}],
      "request":{"method":"POST",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}/issues",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"},
        "body":"{\"title\":\"{{ input.title }}\",\"body\":\"{{ input.body }}\"}"},
      "response_map":{"number":"$.number","url":"$.html_url"}},
    {"name":"close_issue","label":"Close issue",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true},
                 {"name":"number","type":"int","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"PATCH",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}/issues/{{ input.number }}",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"},
        "body":"{\"state\":\"closed\"}"},
      "response_map":{"ok":"$.id"}},
    {"name":"comment_issue","label":"Comment on issue",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true},
                 {"name":"number","type":"int","required":true},
                 {"name":"body","type":"string","required":true}],
      "outputs":[{"name":"comment_id","type":"int"}],
      "request":{"method":"POST",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}/issues/{{ input.number }}/comments",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"},
        "body":"{\"body\":\"{{ input.body }}\"}"},
      "response_map":{"comment_id":"$.id"}},
    {"name":"create_pr","label":"Create pull request",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true},
                 {"name":"title","type":"string","required":true},
                 {"name":"head","type":"string","required":true,"help":"Source branch"},
                 {"name":"base","type":"string","required":true,"help":"Target branch"},
                 {"name":"body","type":"string"}],
      "outputs":[{"name":"number","type":"int"},{"name":"url","type":"string"}],
      "request":{"method":"POST",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}/pulls",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"},
        "body":"{\"title\":\"{{ input.title }}\",\"head\":\"{{ input.head }}\",\"base\":\"{{ input.base }}\",\"body\":\"{{ input.body }}\"}"},
      "response_map":{"number":"$.number","url":"$.html_url"}},
    {"name":"list_issues","label":"List repo issues",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true},
                 {"name":"state","type":"string","default":"open"}],
      "outputs":[{"name":"issues","type":"array"}],
      "request":{"method":"GET",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}/issues?state={{ input.state }}",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"}},
      "response_map":{"issues":"$"}},
    {"name":"get_repo","label":"Get repository info",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true}],
      "outputs":[{"name":"repo","type":"object"}],
      "request":{"method":"GET",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"}},
      "response_map":{"repo":"$"}},
    {"name":"create_release","label":"Create release",
      "inputs":[{"name":"owner","type":"string","required":true},
                 {"name":"repo","type":"string","required":true},
                 {"name":"tag_name","type":"string","required":true},
                 {"name":"name","type":"string"},
                 {"name":"body","type":"string"}],
      "outputs":[{"name":"id","type":"int"},{"name":"html_url","type":"string"}],
      "request":{"method":"POST",
        "url":"https://api.github.com/repos/{{ input.owner }}/{{ input.repo }}/releases",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Accept":"application/vnd.github+json"},
        "body":"{\"tag_name\":\"{{ input.tag_name }}\",\"name\":\"{{ input.name }}\",\"body\":\"{{ input.body }}\"}"},
      "response_map":{"id":"$.id","html_url":"$.html_url"}}
  ]
}'::jsonb WHERE slug = 'github';

-- ============ HUBSPOT ============
UPDATE integrations SET manifest = '{
  "auth":{"type":"api_key","fields":[{"name":"token","label":"Private App Token"}]},
  "actions":[
    {"name":"create_contact","label":"Create or update contact",
      "inputs":[{"name":"email","type":"string","required":true},
                 {"name":"firstname","type":"string"},
                 {"name":"lastname","type":"string"},
                 {"name":"company","type":"string"},
                 {"name":"phone","type":"string"}],
      "outputs":[{"name":"id","type":"string"}]},
    {"name":"get_contact","label":"Get contact by id",
      "inputs":[{"name":"contact_id","type":"string","required":true}],
      "outputs":[{"name":"contact","type":"object"}],
      "request":{"method":"GET",
        "url":"https://api.hubapi.com/crm/v3/objects/contacts/{{ input.contact_id }}",
        "headers":{"Authorization":"Bearer {{ auth.token }}"}},
      "response_map":{"contact":"$"}},
    {"name":"delete_contact","label":"Delete contact",
      "inputs":[{"name":"contact_id","type":"string","required":true}],
      "outputs":[{"name":"ok","type":"boolean"}],
      "request":{"method":"DELETE",
        "url":"https://api.hubapi.com/crm/v3/objects/contacts/{{ input.contact_id }}",
        "headers":{"Authorization":"Bearer {{ auth.token }}"}},
      "response_map":{"ok":"$"}},
    {"name":"create_deal","label":"Create deal",
      "inputs":[{"name":"name","type":"string","required":true},
                 {"name":"amount","type":"number"},
                 {"name":"stage","type":"string"}],
      "outputs":[{"name":"id","type":"string"}],
      "request":{"method":"POST",
        "url":"https://api.hubapi.com/crm/v3/objects/deals",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Content-Type":"application/json"},
        "body":"{\"properties\":{\"dealname\":\"{{ input.name }}\",\"amount\":\"{{ input.amount }}\",\"dealstage\":\"{{ input.stage }}\"}}"},
      "response_map":{"id":"$.id"}},
    {"name":"add_note","label":"Add note to contact",
      "inputs":[{"name":"contact_id","type":"string","required":true},
                 {"name":"note","type":"string","required":true}],
      "outputs":[{"name":"note_id","type":"string"}],
      "request":{"method":"POST",
        "url":"https://api.hubapi.com/crm/v3/objects/notes",
        "headers":{"Authorization":"Bearer {{ auth.token }}","Content-Type":"application/json"},
        "body":"{\"properties\":{\"hs_note_body\":\"{{ input.note }}\",\"hs_timestamp\":\"{{ input.contact_id }}\"},\"associations\":[{\"to\":{\"id\":\"{{ input.contact_id }}\"},\"types\":[{\"associationCategory\":\"HUBSPOT_DEFINED\",\"associationTypeId\":202}]}]}"},
      "response_map":{"note_id":"$.id"}},
    {"name":"list_contacts","label":"List recent contacts",
      "inputs":[{"name":"limit","type":"int","default":25}],
      "outputs":[{"name":"contacts","type":"array"}],
      "request":{"method":"GET",
        "url":"https://api.hubapi.com/crm/v3/objects/contacts?limit={{ input.limit }}",
        "headers":{"Authorization":"Bearer {{ auth.token }}"}},
      "response_map":{"contacts":"$.results"}}
  ]
}'::jsonb WHERE slug = 'hubspot';
